### ISSUE TITLE
ppn2ocr: Gracefully handle METS that already contains IIIF URL

### ISSUE THREAD

**Issue by kba** [qurator-spk/ocrd-galley#54]
E.g

```
ppn2ocr PPN1048290832
```

yields

```
Traceback (most recent call last):                                                                                    
  File "/home/kba/bin/ppn2ocr", line 186, in <module>                                                                 
    ppn2ocr()                                                                                                         
  File "/home/kba/monorepo/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__           
    return self.main(*args, **kwargs)
  File "/home/kba/monorepo/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/kba/monorepo/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kba/monorepo/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/kba/bin/ppn2ocr", line 175, in ppn2ocr
    make_workspace(ppn, ppn)
  File "/home/kba/bin/ppn2ocr", line 137, in make_workspace
    url_iiif_full = iiif_url_for_dms_url(old_url, ppn, 'full', format_)
  File "/home/kba/bin/ppn2ocr", line 54, in iiif_url_for_dms_url
    raise ValueError(f"Unexpected URL {dms_url}")
ValueError: Unexpected URL https://content.staatsbibliothek-berlin.de/dc/PPN1048290832-00000001/full/max/0/default.jpg
```

So if `DEFAULT` already contains IIIF instead of legacy DMS URL, these should be kept as-is.

**Comment by mikegerber** [comment]
This is one of the bugs I have been waiting for 😍

**Comment by mikegerber** [comment]
As of b2e02db, ppn2ocr now also handles IIIF URLs as input. MAX is still overwritten with generated URLs, though - this is subject to change in the future (that is, validation of MAX instead of overwriting.)
